resources:
  repositories:
  - repository: self
    type: git
jobs: 
 - job: Phase_1 
   displayName: Assessment
   cancelTimeoutInMinutes: 1
   pool:
     name: Azure Pipelines
     vmImage: windows-latest
   steps:
   - checkout: self
     clean: False
     submodules: recursive
     persistCredentials: True
   - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@2
     displayName: 'Run PoliCheck'
     inputs:
       targetType: F
       optionsFC: 1
       optionsUEPATH: '$(Build.SourcesDirectory)/.azure/pipelines/policheck-exclusion.xml'
       optionsSEV: '1|2|3|4'
   - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@2
     displayName: 'Policheck Break Build'
     inputs:
       GdnBreakAllTools: false
       GdnBreakGdnToolPoliCheck: true
   - task: securedevelopmentteam.vss-secure-development-tools.build-task-report.SdtReport@2
     displayName: 'Create Security Analysis Report'
     inputs:
       GdnExportTsvFile: true
       GdnExportAllTools: false
       GdnExportGdnToolPoliCheck: true
       GdnExportGdnToolPoliCheckSeverity: Error
   - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@3
     displayName: 'Publish Security Analysis Logs'
   - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@2
     displayName: 'Post Analysis'
     inputs:
       GdnBreakAllTools: false
       GdnBreakGdnToolPoliCheck: true
