apiVersion: v2
name: garnet
description: A Helm chart for Microsoft Garnet
type: application
version: 0.2.0
appVersion: Version.props
home: https://github.com/microsoft/garnet
icon: https://avatars.githubusercontent.com/u/6154722?s=200&v=4

keywords:
- scalable
- key-value
- cache
- cluster
- store
- remote
- persistent
- concurrent
- low-latency
- cache-storage
- hash-table
- larger-the-memory

sources:
- https://github.com/microsoft/garnet.git

maintainers: []
